//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class LoginEMP
    {
        public int id { get; set; }
        [DisplayName("UserName")]
        [Required]
        public string username { get; set; }
        [DisplayName("Password")]
        [DataType(DataType.Password)]
        [Required]
        public string password { get; set; }
    }
}
